# Buildpacks to include in builder
[[buildpacks]]
uri = "."

# Order used for detection
[[order]]
    # This buildpack will display build-time information (as a dependency)
    [[order.group]]
    id = "mcasperson/java"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "heroku-20"
run-image = "heroku/pack:20"
build-image = "heroku/pack:20-build"
